### PR TITLE
Unit test for Post business logic.

### PR DESCRIPTION
**Pull request by DamionSilver**
We added TDD testing for business model Post.cs.

### CODE REVIEW

**Review by escalonn — CHANGES_REQUESTED** [review]
the tests need their own PR into a branch that is not main.
followed by a _separate PR_ with the minimal implementation into that same branch.
that same branch meanwhile has its own separate PR as well, to main, which is merged at the end when it's all ready

**Comment by nosyrbllewe** [comment]
There were separate branches tests failing and tests passing (though we did forget to add the labels tdd-fail and tdd-pass). The branches were just deleted after they had a pull request into PostTesting (this branch). I don't see what the issue is. Is the issue with the last commit not being its own pull request? Did you want a feature branch that you want PostTesting to make a pull request into?

**Comment by DamionSilver** [comment]
> the tests need their own PR into a branch that is not main.
> followed by a _separate PR_ with the minimal implementation into that same branch.
> that same branch meanwhile has its own separate PR as well, to main, which is merged at the end when it's all ready

**Comment by escalonn** [comment]
@nosyrbllewe i didn't notice how there were separate PRs here because i hadn't had my review requested on them

**Pull request closed without merging**
