### PR TITLE
Ft seed data

### PR DESCRIPTION
**Pull request by mgoodm**
seed some data into the database from the context class

### CODE REVIEW

**Review by nodeJayS — COMMENTED** [review]
Seeded data looks fine

**Review by escalonn — COMMENTED** [review]
need to add a migration any time you modify the EF model including seed data.

**Review by nodeJayS — COMMENTED** [review]
Looks like its been properly generated

**Comment by escalonn** [comment]
branch is out of date

**Review by escalonn — APPROVED** [review]

**Pull request merged**
